### PR TITLE
Better error message if s3 deletion takes longer than 30s.

### LINKED ISSUE #279: timeout on s3 delete
Dropping a s3 with (a somewhat large) content (cloudctl s3 delete --force ...) gets a timeout

Error: Delete "https://api.fits.cloud/cloud/v1/s3": context deadline exceeded

The backend obviously still actually carries out the request since a while later the s3 is gone, but the timeout is irritating :-D

### PR DESCRIPTION
**Pull request by Gerrit91**
Closes #279.

### CODE REVIEW

File: cmd/s3.go [hunk 1]
```diff
@@ -247,6 +249,9 @@ func (c *config) s3Delete() error {
 
 	response, err := c.cloud.S3.Deletes3(request, nil)
 	if err != nil {
+		if errors.Is(err, context.DeadlineExceeded) {
```
Comment (majst01) [inline cmd/s3.go:252]: Another approach would be to simply put this into background and tell the user that the deletion will take a while to complete

Comment (Gerrit91) [reply cmd/s3.go:252]: So you want to keep the server connection open? Not sure if there are other timeouts involved which will cancel the request prematurely. 🤔

**Review by majst01 — APPROVED** [review]
